In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("House_Price.csv")

In [4]:
df.head()

,Flat_Price,EMI_Starts,BHK,css-11nfaq3,Unnamed: 4,HOUSE_TYPE,Unnamed: 6,Unnamed: 7,Purpose,Location,Area_Type,Total_Sq.ft,Price_per_sq.ft,Owner_name,Owner_type
0,₹8.5 Cr,₹4.22 Lacs,6 BHK,6.0,BHK,Independent House,Independent,House,for sale in,"Ballygunge, Kolkata",Build Up Area,4200 sq.ft,₹20.24 K/sq.ft,Abhijit Chakraborty,Housing Expert
1,₹45.0 L,₹23.83 K,3 BHK,3.0,BHK,Independent House,Independent,House,for sale in,"Barrackpore, Kolkata",Build Up Area,1400 sq.ft,₹3.21 K/sq.ft,Virtual Reality,Housing Expert
2,₹1.35 Cr,₹67.02 K,3 BHK,3.0,BHK,Independent House,Independent,House,for sale in,"Santoshpur, Kolkata",Build Up Area,2500 sq.ft,₹5.40 K/sq.ft,AveNew Properties,Housing Expert
3,₹60.0 L,₹31.77 K,5 BHK,5.0,BHK,Independent House,Independent,House,for sale in,"Sarsuna, Kolkata",Build Up Area,1100 sq.ft,₹5.45 K/sq.ft,Ganapati Real Estate,Housing Expert
4,₹52.0 L,₹27.54 K,4 BHK,4.0,BHK,Independent House,Independent,House,for sale in,"Madhyamgram, Kolkata",Build Up Area,900 sq.ft,₹5.78 K/sq.ft,Third Eye Consulting,Housing Expert

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 3956 entries, 0 to 3967
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flat_Price       3956 non-null   str
 1   EMI_Starts       3956 non-null   str
 2   BHK              3956 non-null   str
 3   css-11nfaq3      3956 non-null   float64
 4   Unnamed: 4       3956 non-null   str
 5   HOUSE_TYPE       3956 non-null   str
 6   Unnamed: 6       3956 non-null   str
 7   Unnamed: 7       3956 non-null   str
 8   Purpose          3956 non-null   str
 9   Location         3956 non-null   str
 10  Area_Type        3956 non-null   str
 11  Total_Sq.ft      3956 non-null   str
 12  Price_per_sq.ft  3956 non-null   str
 13  Owner_name       3956 non-null   str
 14  Owner_type       3956 non-null   str
dtypes: float64(1), str(14)
memory usage: 494.5 KB

In [5]:
df.describe()

       css-11nfaq3
count  3966.000000
mean      4.742436
std       2.440006
min       1.000000
25%       3.000000
50%       4.000000
75%       6.000000
max      10.500000

In [8]:
df.isnull().sum()

Flat_Price         0
EMI_Starts         0
BHK                0
css-11nfaq3        0
Unnamed: 4         0
HOUSE_TYPE         0
Unnamed: 6         0
Unnamed: 7         0
Purpose            0
Location           0
Area_Type          0
Total_Sq.ft        0
Price_per_sq.ft    0
Owner_name         0
Owner_type         0
dtype: int64

In [7]:
df = df.dropna()

In [12]:
df['Flat_Price'].head()

0     ₹8.5 Cr
1     ₹45.0 L
2    ₹1.35 Cr
3     ₹60.0 L
4     ₹52.0 L
Name: Flat_Price, dtype: str

In [13]:
df['Total_Sq.ft'].head()

0    4200 sq.ft
1    1400 sq.ft
2    2500 sq.ft
3    1100 sq.ft
4     900 sq.ft
Name: Total_Sq.ft, dtype: str

In [14]:
df['BHK'].head()

0    6 BHK
1    3 BHK
2    3 BHK
3    5 BHK
4    4 BHK
Name: BHK, dtype: str

In [19]:
df['BHK'].dtype

dtype('int64')

In [18]:
df['BHK'] = df['BHK'].astype(str).str.extract(r'(\d+)').astype(int)

In [20]:
df['Total_Sq.ft'] = df['Total_Sq.ft'].str.replace('[^0-9.]', '', regex=True)
df['Total_Sq.ft'] = df['Total_Sq.ft'].astype(float)

In [21]:
def convert_price(price):
    price = price.replace('₹', '').strip()
    
    if 'Cr' in price:
        return float(price.replace('Cr', '').strip()) * 10000000
    elif 'L' in price:
        return float(price.replace('L', '').strip()) * 100000
    else:
        return None

df['Flat_Price'] = df['Flat_Price'].apply(convert_price)

In [22]:
df[['Flat_Price']].head()

   Flat_Price
0  85000000.0
1   4500000.0
2  13500000.0
3   6000000.0
4   5200000.0

In [23]:
X = df[['Total_Sq.ft', 'BHK']]
y = df['Flat_Price']

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_pred)

895176786588295.8

In [28]:
model.predict([[1500, 3]])

d:\ai-ml-learning\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([6205130.91874774])

In [29]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3765531220814585

In [31]:
df['Price_per_sq.ft'] = df['Price_per_sq.ft'].str.replace('[^0-9.]', '', regex=True)

df['Price_per_sq.ft'] = pd.to_numeric(df['Price_per_sq.ft'], errors='coerce')

In [32]:
df['Price_per_sq.ft'].isnull().sum()

np.int64(3894)

In [33]:
df = df.dropna(subset=['Price_per_sq.ft'])

In [34]:
df['Price_per_sq.ft'].head(10)

44      514.0
61      514.0
227     204.0
247     204.0
749     350.0
770     350.0
823     796.0
842     796.0
1283    806.0
1303    806.0
Name: Price_per_sq.ft, dtype: float64

In [35]:
X = df[['Total_Sq.ft', 'BHK', 'Price_per_sq.ft']]
y = df['Flat_Price']

In [36]:
df = pd.get_dummies(df, columns=['Location'], drop_first=True)

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3765531220814585

In [38]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.751949259465923

In [ ]:
### Model Comparison

- Linear Regression R²: 0.37 ['Total_Sq.ft', 'BHK']
- Random Forest R²: 0.75  ['Total_Sq.ft', 'BHK', 'Price_per_sq.ft']

### Conclusion

Random Forest performed significantly better due to its ability to capture non-linear relationships in housing data.

In [40]:
df.columns

Index(['Flat_Price', 'EMI_Starts', 'BHK', 'css-11nfaq3', 'Unnamed: 4',
       'HOUSE_TYPE', 'Unnamed: 6', 'Unnamed: 7', 'Purpose', 'Area_Type',
       'Total_Sq.ft', 'Price_per_sq.ft', 'Owner_name', 'Owner_type',
       'Location_Bangaon, Kolkata', 'Location_Barasat, Kolkata',
       'Location_Baruipur, Kolkata', 'Location_Behala, Kolkata',
       'Location_Bhatpara, Kolkata', 'Location_Dakshineswar, Kolkata',
       'Location_Dunlop, Kolkata', 'Location_Duttapukur, Kolkata',
       'Location_Garden Reach, Kolkata', 'Location_Habra, Kolkata',
       'Location_Jodhpur Park, Kolkata', 'Location_Kasba, Kolkata',
       'Location_Khardah, Kolkata', 'Location_Khidirpur, Kolkata',
       'Location_Maheshtala, Kolkata', 'Location_Naihati, Kolkata',
       'Location_Nayabad, Kolkata', 'Location_Netaji Nagar, Kolkata',
       'Location_New Barrakpur, Kolkata', 'Location_Paschim Putiary, Kolkata',
       'Location_Picnic Garden, Kolkata', 'Location_Purba Putiary, Kolkata',
       'Location_Sewli Telinipara, Kolkata', 'Location_Sinthi, Kolkata',
       'Location_Thakurpukur, Kolkata', 'Location_Tollygunge, Kolkata'],
      dtype='str')

In [41]:
X = df.drop('Flat_Price', axis=1)
y = df['Flat_Price']

In [42]:
r2_score(y_test, y_pred)

0.751949259465923

In [43]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7507493426418445

In [44]:
X = df.drop('Flat_Price', axis=1)
y = df['Flat_Price']

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [48]:
X = df.drop('Flat_Price', axis=1)

In [49]:
df.dtypes

Flat_Price                            float64
EMI_Starts                                str
BHK                                     int64
css-11nfaq3                           float64
Unnamed: 4                                str
HOUSE_TYPE                                str
Unnamed: 6                                str
Unnamed: 7                                str
Purpose                                   str
Area_Type                                 str
Total_Sq.ft                           float64
Price_per_sq.ft                       float64
Owner_name                                str
Owner_type                                str
Location_Bangaon, Kolkata                bool
Location_Barasat, Kolkata                bool
Location_Baruipur, Kolkata               bool
Location_Behala, Kolkata                 bool
Location_Bhatpara, Kolkata               bool
Location_Dakshineswar, Kolkata           bool
Location_Dunlop, Kolkata                 bool
Location_Duttapukur, Kolkata             bool
Location_Garden Reach, Kolkata           bool
Location_Habra, Kolkata                  bool
Location_Jodhpur Park, Kolkata           bool
Location_Kasba, Kolkata                  bool
Location_Khardah, Kolkata                bool
Location_Khidirpur, Kolkata              bool
Location_Maheshtala, Kolkata             bool
Location_Naihati, Kolkata                bool
Location_Nayabad, Kolkata                bool
Location_Netaji Nagar, Kolkata           bool
Location_New Barrakpur, Kolkata          bool
Location_Paschim Putiary, Kolkata        bool
Location_Picnic Garden, Kolkata          bool
Location_Purba Putiary, Kolkata          bool
Location_Sewli Telinipara, Kolkata       bool
Location_Sinthi, Kolkata                 bool
Location_Thakurpukur, Kolkata            bool
Location_Tollygunge, Kolkata             bool
dtype: object

In [50]:
X = df.select_dtypes(include=['int64', 'float64']).drop('Flat_Price', axis=1)
y = df['Flat_Price']

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9367515064723648

In [53]:
df.select_dtypes(include=['int64', 'float64']).corr()['Flat_Price'].sort_values(ascending=False)

Flat_Price         1.000000
Total_Sq.ft        0.917350
BHK                0.384182
css-11nfaq3        0.384182
Price_per_sq.ft    0.052113
Name: Flat_Price, dtype: float64

In [54]:
import pandas as pd

importance = model.feature_importances_

feature_names = X.columns

feat_imp = pd.Series(importance, index=feature_names)
feat_imp.sort_values(ascending=False)

Total_Sq.ft        0.957752
Price_per_sq.ft    0.029761
css-11nfaq3        0.006899
BHK                0.005588
dtype: float64

In [55]:
X = X.drop(['css-11nfaq3'], axis=1)

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9182006546255244

In [57]:
X = df[['Total_Sq.ft']]

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8923912467130384

In [ ]:
Feature importance analysis showed that Total_Sq.ft was the dominant predictor, contributing to most of the model’s performance, while other features provided incremental improvements.

In [ ]:
I built a house price prediction model using Python and Scikit-learn. Initially, Linear Regression gave poor results, so I improved the dataset through cleaning and feature engineering. Using Random Forest, I achieved an R² score of 0.93. Feature importance analysis showed that Total_Sq.ft was the most significant predictor.